### ISSUE TITLE
const / let使うとgulpがこける

### ISSUE THREAD

**Issue by hideokamoto** [contiki9/shu-1blog#4]
varつかいたくない

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Users/dc_hideokamoto/develop/html/shu-1blog/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at apply (/Users/dc_hideokamoto/develop/html/shu-1blog/node_modules/gulp-uglify/node_modules/lodash/_apply.js:16:25)
    at wrapper (/Users/dc_hideokamoto/develop/html/shu-1blog/node_modules/gulp-uglify/node_modules/lodash/_createCurry.js:41:12)
    at /Users/dc_hideokamoto/develop/html/shu-1blog/node_modules/gulp-uglify/lib/minify.js:54:15
    at DestroyableTransform._transform (/Users/dc_hideokamoto/develop/html/shu-1blog/node_modules/gulp-uglify/composer.js:10:23)
    at DestroyableTransform.Transform._read (/Users/dc_hideokamoto/develop/html/shu-1blog/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/dc_hideokamoto/develop/html/shu-1blog/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/dc_hideokamoto/develop/html/shu-1blog/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/Users/dc_hideokamoto/develop/html/shu-1blog/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/Users/dc_hideokamoto/develop/html/shu-1blog/node_modules/readable-stream/lib/_stream_writable.js:334:11)
Segmentation fault: 11
```

**Comment by mismith0227** [comment]
@hideokamoto @contiki9 やっておきました。
https://github.com/contiki9/shu-1blog/pull/6

**Comment by hideokamoto** [comment]
🍻
